# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NCORE": "00_core.ipynb",
         "get_process_func": "00_core.ipynb",
         "bson_to_jpeg": "00_core.ipynb"}

modules = ["process_bson.py"]

doc_url = "https://bwolfson97.github.io/cdiscount/"

git_url = "https://github.com/bwolfson97/cdiscount/tree/main/"

def custom_doc_links(name): return None
