# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"save_images": "00_process_bson.ipynb",
         "get_mapping": "00_process_bson.ipynb",
         "bson_to_jpeg": "00_process_bson.ipynb",
         "get_image_path": "01_find_duplicates.ipynb",
         "get_hash": "01_find_duplicates.ipynb",
         "MAX_IMAGES_PER_PRODUCT": "01_find_duplicates.ipynb",
         "process_row": "01_find_duplicates.ipynb",
         "process_df": "01_find_duplicates.ipynb",
         "contains_multiple_values_in_column": "01_find_duplicates.ipynb",
         "appears_in_multiple_categories": "01_find_duplicates.ipynb",
         "appears_in_train_and_test": "01_find_duplicates.ipynb",
         "set_index_and_sort": "01_find_duplicates.ipynb",
         "find_duplicates": "01_find_duplicates.ipynb",
         "get_duplicated_image_idxs": "02_process_duplicates_image_level.ipynb",
         "get_test_imgs_to_train_categories": "02_process_duplicates_image_level.ipynb",
         "get_image_level_csvs": "02_process_duplicates_image_level.ipynb"}

modules = ["process_bson.py",
           "find_duplicates.py",
           "process_duplicates_image_level.py"]

doc_url = "https://bwolfson97.github.io/cdiscount/"

git_url = "https://github.com/bwolfson97/cdiscount/tree/main/"

def custom_doc_links(name): return None
